#ifndef PLAYBACKPOLICY_H
#define PLAYBACKPOLICY_H

#include "playbackqueue.h"
#include "playlist.h"

// [PlaybackPolicy] is unique to [Playlist], queue shared. On a playlist tab
// switch, a new [PlaybackPolicy] is set for [PlaybackManager]
class PlaybackPolicy {
public:
  // PlaybackPolicy(PlaybackQueue &);
  PlaybackPolicy();
  virtual void setPlaylist(const Playlist *) = 0;
  virtual int nextPk() = 0;
  virtual int prevPk() = 0;
  // set [currentPk], should call this method whenever a new song is played by
  // manual selection or queue. Song generated by [PlaybackPolicy] is tracked
  // within the class. This method is mainly for tracking of songs that is
  // manually selected and avoid accessing [PlaybackQueue]. Derived class may
  // choose how to use the manual song information.
  virtual void setCurrentPk(int);

private:
  virtual void reset() = 0;

protected:
  int currentPk = -1;
  const Playlist *playlist;
};

#endif // PLAYBACKPOLICY_H
